name: Update Changelog

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Update changelog.html
        if: "!contains(github.event.head_commit.message, '[skip changelog]')"
        run: |
          # Get commit details
          COMMIT_HASH_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          COMMIT_MSG=$(git log -1 --pretty=%s)
          COMMIT_DATE=$(date +'%d/%m/%Y')
          REPO_URL="https://github.com/${{ github.repository }}"

          # Create the new HTML table row.
          NEW_ROW="                        <tr>\n                            <td>${COMMIT_MSG}</td>\n                            <td>${COMMIT_DATE}</td>\n                            <td><a target=\"_blank\" class=\"table-link\" href=\"${REPO_URL}/commit/${{ github.sha }}\">${COMMIT_HASH_SHORT}</a></td>\n                        </tr>\n"

          # Find the <tbody> tag and insert the new row right after it. This is the robust command.
          sed -i "s|<tbody>|&\n${NEW_ROW}|" changelog.html

      - name: Commit updated changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update changelog [skip changelog]"
          file_pattern: changelog.html
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com